# Match on regex to select columns of various types
bin_col_exprs = ['ADDEPEV[0-9]', 'ASTHMA[0-9]', 'ASTHNOW', 'BLIND', 'CADULT', 'CCLGHOUS', 'COLGHOUS', 'CELLFON[0-9]', 'CHCCOPD[0-9]', 'CHCKDNY[0-9]', 'CHCOCNCR', 'CHCSCNCR', 'CSTATE[0-9]',
                 'CTELENM[0-9]', 'CTELENUM[0-9]', 'CVDCRHD[0-9]', 'CVDINFR[0-9]', 'DEAF', 'DECIDE', 'DIABETE[0-9]', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'EXERANY[0-9]', 'FLUSHOT[0-9]',
                 'HADHYST[0-9]', 'HADPAP[0-9]', 'HAVARTH[0-9]', 'HLTHPLN[0-9]', 'HPVTEST', 'LANDLINE', 'MEDCOST', 'NUMHHOL[0-9]', 'PCPSAAD[0-9]', 'PCPSADI[0-9]', 'PCPSARE[0-9]',
                 'PNEUVAC[0-9]', 'PREGNANT', 'PSATEST[0-9]', 'PVTRESD[0-9]', 'SAFETIME', 'SMOKE100', 'STATERE[0-9]', 'STOPSMK[0-9]', 'VETERAN[0-9]', 'PDIABTST', 'INSULIN', 'DIABEYE',
                 'DIABEDU', 'MEDICARE', 'NOCOV121', 'CIMEMLOS', 'CDDISCUS', 'CAREGIV[0-9]', 'CRGVEXPT', 'CSRVINSR', 'CSRVDEIN', '_CHISPNC', '_RFHLTH', '_HCVU651', '_TOTINDA', '_MICHD', '_LTASTH1',
                 '_DRDXAR1', '_HISPANC', '_RFBMI5', '_RFBING5', '_RFMAM21', '_MAM5022', '_COL10YR', '_AIDTST[0-9]']

cat_col_exprs = ['CHECKUP[0-9]', 'RSPSTAT[0-9]', 'DISPCODE', 'DRNK3GES', 'EDUCA', 'EMPLOY[0-9]', 'GENHLTH', 'HOWLONG', 'HPLSTTST', 'IMFVPLA[0-9|A-Z]', 'INCOME2', 'LADULT', 'LASTDEN[0-9]',
                 'LASTPAP[0-9]', 'LASTSMK[0-9]', 'MARITAL', 'NUMADULT', 'PERSDOC[0-9]', 'RENTHOM[0-9]', 'RMVTETH[0-9]', 'SEATBELT', 'SEX[0-9]', 'SMOKDAY[0-9]', 'USENOW[0-9]', '_STATE',
                 'PREDIAB[0-9]', 'EYEEXAM[0-9]', 'HLTHCVR[0-9]', 'DELAYME[0-9]', 'CARERCVD', 'CDHOUSE', 'CDASSIST', 'CDHELP', 'CDSOCIAL', 'CRGVREL[0-9]', 'CRGVLNG[0-9]', 'CRGVHRS[0-9]',
                 'CRGVPRB[0-9]', 'USEMRJN[0-9]', 'RSNMRJN[0-9]', 'ADPLEAS[0-9]', 'ADDOWN[0-9]', 'FEELNERV', 'STOPWORY', 'CNCRDIFF', 'CNCRTYP[0-9]', 'CSRVTRT[0-9]', 'CSRVDOC[0-9]',
                 'SOMALE', 'SOFEMALE', 'TRNSGNDR', 'MSCODE', 'QSTVER', 'QSTLANG', '_METSTAT', '_URBSTAT', '_IMPRACE', '_CRACE1', '_CPRACE', '_PHYS14D', '_MENT14D', '_PRACE[0-9]', '_MRACE[0-9]',
                 '_RACE', '_AGEG5YR', '_AGE80', '_AGE_G', '_BMI5CAT', '_EDUCAG', '_INCOMG', '_SMOKER[0-9]', ' _RFSMOK[0-9]']

combo_col_exprs = ['BLDSUGAR', 'FEETCHK[0-9]']

cont_col_exprs = ['ALCDAY[0-9]', 'AVEDRNK[0-9]', 'CHILDREN', 'CPDEMO1B', 'DIABAGE[0-9]', 'DRNKDRI[0-9]', 'FALLINJ[0-9]', 'MAXDRNKS', 'SLEPTIM[0-9]', 'HEIGHT[0-9]', 'HHADULT',
                  'MENTHLTH', 'NUMMEN', 'NUMWOMEN', 'NUMPHON[0-9]', 'PHYSHLTH', 'POORHLTH', 'WEIGHT[0-9]', 'DOCTDIAB', 'CHKHEMO[0-9]', 'FEETCHK', 'DRVISITS', 'MARIJAN[0-9]', 'NUMBURN[0-9]',
                  'LCSFIRST', 'LCSLAST', 'LCSNUMCG', 'CNCRAGE', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', '_CHLDCNT']


other_col_exprs = ['FLSHTMY[0-9]', 'FMONTH', 'IDATE', 'IDAY', 'IMONTH', 'IYEAR', 'SEQNO', '_PSU', 'CTYCODE[0-9]', 'ZIPCODE[0-9]', 'DLYOTHER', 'TYPEWORK', 'TYPEINDS']